apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4uiy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-4uiy@sha256:53973498e8db59c14d21aaa0b6d1e62cd7c200fcdee989634c6d634e29661518
        name: my-nodejs
        resources: {}
status: {}
